spring.application.name=demo
server.port=8081

spring.security.oauth2.client.registration.keycloak.client-id=OIDC
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://127.0.0.1:8080/realms/SpringBootSecurity
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred-username

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8080/realms/SpringBootSecurity

